name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            output-name: hello-linux
          - os: macOS-latest
            output-name: hello-mac
          - os: windows-latest
            output-name: hello-windows.exe

    steps:

      - run: dart pub get update
      - run: mkdir build
      - run: dart compile exe bin/main.dart
      - uses: actions/upload-artifact@v1
        with:
          name: native-executables
          path: build
